export type BillStatus = "unpaid" | "partial" | "paid";

export type Bill = {
    id: string;
    user_id: string;
    bill_no: string;
    customer_name: string;
    customer_phone: string | null;
    bill_date: string;
    received_amount: string;
    total_amount: string;
    status: BillStatus;
    created_at: string;
    updated_at: string;
};

export type BillItem = {
    id: string;
    bill_id: string;
    user_id: string;
    sr_no: number;
    description: string;
    quantity: string;
    weight: string | null;
    rate: string;
    amount: string;
    created_at: string;
};

// bill_no is generated by the DB trigger `assign_bill_number`.
// total_amount is populated by the `bill_items_update_total` trigger.
// status is a STORED generated column derived from total/received.
export type BillInsert = Omit<
    Bill,
    "id" | "bill_no" | "total_amount" | "status" | "created_at" | "updated_at"
> & {
    bill_no?: string;
    total_amount?: string;
};

export type BillUpdate = Partial<
    Omit<Bill, "id" | "user_id" | "status" | "created_at" | "updated_at">
>;

export type BillItemInsert = Omit<BillItem, "id" | "amount" | "created_at">;

type EmptyRecord = Record<string, never>;

export type Database = {
    public: {
        Tables: {
            bills: {
                Row: Bill;
                Insert: BillInsert;
                Update: BillUpdate;
                Relationships: [];
            };
            bill_items: {
                Row: BillItem;
                Insert: BillItemInsert;
                Update: Partial<BillItemInsert>;
                Relationships: [];
            };
        };
        Views: EmptyRecord;
        Functions: {
            bill_stats: {
                Args: Record<string, never>;
                Returns: {
                    total_count: number;
                    total_revenue: string;
                    outstanding: string;
                    this_month_count: number;
                };
            };
            customer_pendings: {
                Args: Record<string, never>;
                Returns: Array<{
                    customer_name: string;
                    bill_count: number;
                    total_amount: string;
                    received_amount: string;
                    pending_amount: string;
                }>;
            };
        };
        Enums: EmptyRecord;
        CompositeTypes: EmptyRecord;
    };
};

// Derive status from received vs total. Single source of truth for UI.
export function deriveStatus(bill: {
    total_amount: string | number;
    received_amount: string | number;
}): BillStatus {
    const total = Number(bill.total_amount);
    const received = Number(bill.received_amount);
    if (total > 0 && received >= total) return "paid";
    if (received > 0) return "partial";
    return "unpaid";
}
